"Reorganize questions, add code of conduct, solve issue #7 remove pub…
FIUP/Getting-Started pull request #8
Opened 2018-01-12 19:38 UTC by fedsib

### Descrizione delle modifiche

Aggiornamento delle FAQ al fine di:
- Rimuovere le incongruenze dovute alla rimozione del link pubblico
- Riorganizzare le domande / risposte
- Aggiungere riferimenti al Codice di Condotta e alle linee guida per contribuire al FIUP

### Design Alternativi

Nessuno

### Benefici

- Miglior comprensione delle FAQ.

### Possibili regressioni

- Sottoposto a controllo con GNU Aspell per evitare possibili typo.

### Issue coinvolte

#7

2018-01-12 20:39 UTC, sydernee commented
> su MEGA lo spazio gratuito ammonta a 15 GB quota base + 35 GB = 50 GB

I 35 GB extra scadono dopo 180 giorni quindi, dopo 6 mesi, uno torna con i 15GB base.

2018-01-12 21:23 UTC, sydernee requested changes
In generale può andare, a parte la questione dello spazio che secondo me è più importante. (il resto sono più che altro suggerimenti)

2018-01-12 21:23 UTC, sydernee commented on CLOUD_FAQ.md
> +- ***Perché MEGA e non un altro servizio?*** Prima di MEGA, usavamo dropbox. ma i file spesso venivano eliminati per sbaglio (non sempre erano ripristinabili) oppure tentando il ripristino si creavan
> su MEGA lo spazio gratuito ammonta a 15 GB quota base + 35 GB = 50 GB

I 35 GB extra scadono dopo 180 giorni quindi, dopo 6 mesi, uno torna con i 15GB base: motivo per cui secondo me è errato affermare che lo spazio fornito è di 50GB.

2018-01-12 21:23 UTC, sydernee commented on CLOUD_FAQ.md
> +	Se non vuoi che la tua mail sia in balia a tutti, evita di postare il tuo indirizzo email nei gruppi ed usa le altre modalità. Gli indirizzi postati nei gruppi, verranno rimossi subito dopo averti d
"`in balia di tutti`" invece di "`in balia a tutti`"

2018-01-12 21:23 UTC, sydernee commented on CLOUD_FAQ.md
>  - ***A che serve questo spazio cloud?*** Serve a condividere appunti, esami, esercizi ed idee tra studenti iscritti ai corsi di informatica delle lauree triennali e magistrali presso la Scuola di Sci
Sarebbe meglio "`e idee`" al posto di "`ed idee`", in quanto l'uso delle d eufonica [dovrebbe essere limitato ai casi di incontro della stessa vocale](http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/d-eufonica).

2018-01-12 21:23 UTC, sydernee commented on CLOUD_FAQ.md
>  **NOTA:** _Non va utilizzato per condividere codice, per quello c'è l'[organizzazione su GitHub](https://github.com/FIUP/). Secondo le modalità [indicate qui](https://github.com/FIUP/Getting_Started/
Al posto di "indicate qui" metterei "indicate nel repository dedicato" o qualche possibile variante.

2018-01-13 13:21 UTC, fedsib commented
Aggiunte le modifiche richieste.

2018-01-13 13:23 UTC, sydernee approved these changes

2018-01-13 13:25 UTC, merged